### ISSUE TITLE
NVME

### ISSUE THREAD

**Issue by NAGA1337** [marciliocn/void-installer#1]
just so u know that nvme thing doesnt work if your nvme is called /dev/nvme0n1 then its going to think it needs to add 1 number more

**Comment by marciliocn** [comment]
HI @NAGA1337 ...I see yesterday your message... I added a hard code in code to perpass this problem.

In next few days I will verify this issue in a machine with NVMe.

Thank you

**Comment by marciliocn** [comment]
Hi @NAGA1337 ...problem fixed. I refactored the specifc code.

Cheers
